### ISSUE TITLE
DB Persistence?

### ISSUE THREAD

**Issue by Idealien** [wckr/wocker#1]
Wocker looks like a great abstraction for local dev environments for those who want simplicity and the functionality of Docker.

If I destroy the VM my data stays within the host synced folder but the DB (inside docker) is gone.
Is that also the case if I halt the VM since each docker instance is created anew?

Using Wocker, how would you recommend one be able to keep DB data persistent?
Both for multiple uses of same dev site over time as well as multiple dev sites?

**Comment by ixkaito** [comment]
Thanks for using Wocker, and I'm glad that you like it.

First, `$ wocker stop CONTAINER` and `$ wocker kill CONTAINER` will not delete data and DB, whereas `$ wocker rm CONTAINER` will delete both data and DB.

If you only stopped containers, halting the VM would not delete or re-create any files, DB, and containers.
If you do `$ vagrant up` and `$ wocker start CONTAINER`, you will have the exact same environment before `$ vagrant halt`.

I would recommend not destroying but just halting the VM. If you don't need the instance anymore, just do `$ wocker rm CONTAINER`.

One drawback of Wocker is that you cannot run two or more containers at the same time, but it takes just seconds to switch between containers.
Therefore, for multiple uses, you have to `$ wocker stop CONTAINER` first and `$ wocker start ANOTHERCONTAINER` or `$ wocker run [--name CONTAINERNAME]` after that.

I hope this will help.
