### ISSUE TITLE
Any way to rename a container/data folder?

### ISSUE THREAD

**Issue by JonnyBGod** [wckr/wocker#11]
Hi,

is there any simple way to rename a container/data folder?

**Comment by junonet** [comment]
me,too.

**Comment by ixkaito** [comment]
Do you mean the `data` folder in your local machine?
Just change `./data` in `config.vm.synced_folder "./data", "/home/core/data", create: true, id: "core", :nfs => true, :mount_options => ['nolock,vers=3,udp']` to anything else.
Then `$ vagrant up`.

**Comment by JonnyBGod** [comment]
No, sorry for poor explanation.

I mean ./data/wocker to .data/SOMETHING

And I dont mean creating a new container. The this is that I already worked a lot on a project under ./data/wocker and would like to change the folder to the project name.

**Comment by ixkaito** [comment]
I see. Which version are you using?
You can check it by `core@wocker wocker version`.

**Comment by JonnyBGod** [comment]
Version: 0.3.1

**Comment by ixkaito** [comment]
When you create a new container, if you have a folder same as the container name, Wocker will use the folder.
1. Stop the running container
2. Rename  the folder (e.g. wocker -> myproject)
3. Create a new container named myproject

```
core@wocker ~ $ wocker run --name myproject
```

If you need the database of the old container, export it before stopping container.

```
core@wocker ~ $ wocker exec -it wocker bash
```

```
root@****:/var/www/wordpress# wp --allow-root db export
```

Then import it after creating a new one

```
core@wocker ~ $ wocker exec -it myproject bash
```

```
root@****:/var/www/wordpress# wp --allow-root db import wordpress.sql
```

**Comment by junonet** [comment]
I'm a designer not familiar with CLI.

In my case, I wanted to create a container and assign a specific name but not rename an existing folder.

I can create containers by using `core@wocker ~ $ wocker run`, 
but the folder name would be something like this: `/data/nostalgic_blackwell`

I know I have to use the example `core@wocker ~ $ wocker run --name wp`,

I'd thought I have to modify `name`: `core@wocker ~ $ wocker run --hogehoge wp`.
(I mistook `wp` for a command)

However, after running `core@wocker ~ $ wocker run --name hogehoge`, `hogehoge` folder was created.

I mistook the meaning of `name`.

It seems lighter than VCCW. I'll use it.
Thanks.

## 

黒い画面がほとんどわかっていないデザイナーです。
日本語で失礼します。

私の場合は、後から、作ったdataフォルダの名前を変更するのではなく、任意の名前をつけたコンテナが作りたかったのです。

core@wocker ~ $ wocker run

だと、新規のコンテナが作れるのですが、
/data/nostalgic_blackwell
のようになってしまう。

で、例えの
core@wocker ~ $ wocker run --name wp
を使うのですが、

フォルダに名前をつけるので、「name」のところ
core@wocker ~ $ wocker run --hogehoge wp
だと思っていました。
（ 「wp」は、ワードプレスを入れる指示かと。。。）

しかし、
core@wocker ~ $ wocker run --name hogehoge

にした所、問題なくhogehogeフォルダができました。

nameの意味の取り違えでした。

VCCWより軽いし、これから使わせていただきます。
ありがとうございます。

**Comment by ixkaito** [comment]
@junonet 

Thanks! You're right.
`wp` in `core@wocker ~ $ wocker run --name wp` should be your container name.
`--name` is an option of `$ wocker run`.
You can also execute the command like this: `core@wocker ~ $ wocker run --name="wp"`

## 

ありがとうございます！その通りです。
`core@wocker ~ $ wocker run --name wp` では `wp` が自分のコンテナ名になります。
`--name` は `$ wocker run` のオプションです。
このようにコマンドを実行することもできます: `core@wocker ~ $ wocker run --name="wp"`
