### ISSUE TITLE
access mysql inside wocker

### ISSUE THREAD

**Issue by balintgaspar** [wckr/wocker#12]
How can I access mysql inside wocker? I need this because i need export import databases.

Thanks

**Comment by ixkaito** [comment]
You can use a Wocker command `$ wocker exec` to enter a running container, and the simplest way to export / import database is probably using WP-CLI.

**Enter the running container**

```
$ vagrant ssh
```

```
core@wocker ~ $ wocker exec -it CONTAINER bash
```

**WP-CLI**

```
root@****:/var/www/wordpress# wp --allow-root db
```

Note: the --allow-root option is required.
More information about WP-CLI: http://wp-cli.org/

**MySQL**

```
root@****:/var/www/wordpress# mysql -uwordpress -pwordpress
```

**These issues may also help you:**
- Accessing the database from host OS #6
- Sharing DBs across machines #7

I will improve the documentation about this in the future.
