### ISSUE TITLE
How to import an existing site?

### ISSUE THREAD

**Issue by manerix** [wckr/wocker#13]
I began yesterday to use wocker, and I'd to use an existing site on it.

How can I import the sql code to the database, and btw where is the db located. Is phpmyAdmin installed too?

Thanks for the answer

Hubert

**Comment by ixkaito** [comment]
Thanks for using Wocker.

The simplest way to import databases is using WP-CLI.
Here's an example:

**1. Connect to the guest machine via SSH**

```
$ vagrant ssh
```

**2. Run a new container named yourproject**

```
core@wocker ~ $ wocker run --name yourporject
```

**4 Copy or move your MySQL file to yourproject directory in your local machine**
The MySQL file will be synced into the virtual machine and yourproject container.

**3. Enter the running container**

```
core@wocker ~ $ wocker exec -it yourproject bash
```

**4. Import your database (e.g. yourproject.sql ) using WP-CLI command**

```
root@****:/var/www/wordpress# wp --allow-root db import yourproject.sql
```

Note: the --allow-root option is required.
More information about WP-CLI: http://wp-cli.org/

**These issues may also help you:**
- Accessing the database from host OS #6
- Sharing DBs across machines #7

**Comment by manerix** [comment]
Thank you, I'll give it a try
