### ISSUE TITLE
"No synced folder implementation is available for your synced folders" error

### ISSUE THREAD

**Issue by unfulvio** [wckr/wocker#14]
When launching Wocker from a Windows machine I have this error.

```
Bringing machine 'default' up with 'virtualbox' provider...
==> default: Checking if box 'coreos-stable' is up to date...

No synced folder implementation is available for your synced folders!
Please consult the documentation to learn why this may be the case.
You may force a synced folder implementation by specifying a "type:"
option for the synced folders. Available synced folder implementations
are listed below.

docker, nfs, rsync, smb, virtualbox
```

**Comment by ixkaito** [comment]
It seems you need a Vagrant plugin `vagrant-winnfsd` to support NFS on Windows.

```
$ vagrant plugin install vagrant-winnfsd
```

You will also need to declare some sort of network in order for NFS to work.
A private dhcp network is required for NFS to work (on Windows hosts, at least).
Please change the line 49 in the Vagrantfile to:

``` ruby
config.vm.network :private_network, ip: "172.17.8.23", type: "dhcp"
```

Also see: https://github.com/GM-Alex/vagrant-winnfsd

**Comment by unfulvio** [comment]
thanks!

I installed the vagrant plugin and made the config change and I also made sure there was no firewall blocking.

It works and the folder is correctly shared and synced.

but... these changes produced another issue,
when doing first vagrant up after provisioning, when vagrant is executing wocker bash script, it hangs forever when reaching this stage:

```
==> default: 95b278389585:
==> default: Download complete
==> default: 95b278389585: Download complete
==> default: Status: Downloaded newer image for wocker/wocker:latest
==> default: 6164e3349148c602f1c5d07a57182fbf381b25c3e09a8a23b26bd66f32824464
```

I tried running the VM with a GUI but couldn't see errors
http:/wocker.dev won't respond as probably it hasn't finished configuring WordPress and starting processes like Apache

the VM has started and I can SSH to it, though
I tried to kill/stop the wocker container and start a new one
but i still can't get HTTP answers - also tried with vagrant reload

since I don't have an error I'm not sure of the problem - I will try figuring out or just forget about it and use a Linux VM or dual boot to run docker straight

**Comment by ixkaito** [comment]
It seems the plugin works well. I'll add it to the document.

Could you please try to pull the image again, and make sure you added "wocker.dev 172.17.8.23" to your hosts file.

**SSH to the VM**

```
$ vagrant ssh
```

**Remove the existing image**

```
core@wocker ~ $ wocker rmi wocker/wocker:latest
```

**Pull the images again**

```
core@wocker ~ $ wocker pull wocker/wocker:latest
```

This could take a while if your network line speed was low.

**Comment by unfulvio** [comment]
it won't work, still and yes the hosts were updated already

it's hard to pin down these problems on windows machines - I ran into many problems already with Docker and Boot2Docker

I think for the time being I'll continue using a plain Vagrant environment without Docker and try Wocker in a dual boot machine or use Docker from a VM straight

thanks for the help and your efforts in making wocker

**Comment by unfulvio** [comment]
ps tried also to reload the VM with vagrant reload or halt it and provision it again, after the suggested changes, but it will still hang when provisioning - this wasn't happening before using the NFS plugin or by removing NFS and trying VBoxSF - although then with VBoxSF Wocker will provision and run in Windows, it will also respond on http requests via the browser, but CoreOS doesn't support vboxsf and therefore I will not have shared folders on the host machine

**Comment by ixkaito** [comment]
Thanks again. You're right. CoreOS doesn't support vboxsf.

I tried Wocker on Windows yesterday. It seems it has problems when running containers. It works well to pull the image `wocker/wocker:latest` but hangs when executing `wocker run`. I will try to figure out whether it's an issue of Docker or Wocker.

**Comment by unfulvio** [comment]
Thanks to you too, Wocker is a nice tool. If I come up with some idea I will come back. For now I switched back to Linux and of course there aren't problems here. There are many WordPress developers on Windows too but I think working with Docker on Windows is more hard at this moment.

**Comment by matwu37** [comment]
I ran into this problem today, and vagrant just hangs at this point

<code>
==> default: Digest: sha256:d1a22a3e425a30081b04d745c0b219c9c49de6447daffb726e3f3de2347808cb
==> default: Status: Downloaded newer image for wocker/wocker:latest
==> default: ae5c145e09af62670d2b12065c904ece84607c48a8956f99906f878de43b6442
</code>

Is there been a solution yet or Wocker is still not recommend for Windows?

Thanks,

P.S. Wins 10, vagrant 1.7.4, latest cygwin

**Comment by ixkaito** [comment]
Sorry for the inconvenience. NFS synced fold is likely to have problems with all Mac, Windows, and Ubuntu. I'm planning to stop using CoreOS at the next major version. It might also solve this problem. Let me reopen this issue.

**Comment by ixkaito** [comment]
Wocker 1.0.0 is now available. http://wckr.github.io/
Please have a try on Windows. You may have to launch the shell application as an admin to run Wocker.
