### ISSUE TITLE
Connecting database via ssh

### ISSUE THREAD

**Issue by balintgaspar** [wckr/wocker#15]
Hi!
I'm trying to connect to wocker running container's db via Sequel Pro. SSH is succeeded but connection is refused to connect

How can I connect to running container's db? ports? ip?

I tried:

docker inspect --format='{{.NetworkSettings.IPAddress}}' "truevgd"wich gives me an IP address but I can't connect...

Best: Balint.

**Comment by ixkaito** [comment]
Now, you can connect to MySQL from outside the container in version 0.5.0, so GUI tools like Sequel Pro or Workbench are available. Please update Wocker.

#### Update Wocker

```
$ vagrant ssh
```

```
core@wocker ~ $ wocker update
```

Note: you can only connect to the container created by v0.5.0 or later.

#### Information of database

Host: `wocker.dev` (or `172.17.8.23`)
User: `wordpress`
Password: `wordpress`
Database: `wordpress`
Port: `3306`

Before v0.5.0, you couldn't connect to MySQL from outside the container, so GUI tools like Sequel Pro or Workbench were not available.
