### ISSUE TITLE
Add method to choose wordpress version

### ISSUE THREAD

**Issue by ben-barbier** [wckr/wocker#16]
It's very important to test plugin compatibility. (copy of https://github.com/ixkaito/wocker/issues/16)

**Comment by ixkaito** [comment]
I know it's useful to have an option to choose WordPress version, but this will take more time to provision.
Wocker is not aiming at a versatile tool. I'm not planning to add it now, but maybe in the future.
Anyway, thanks :)

**Comment by ixkaito** [comment]
I found a solution about this.
For example, to test with WordPress 3.5.

**1. Run a new container `test`**

```
core@wocker $ wocker run --name test
```

**2. Download version 3.5 using `wp` command**

```
core@wocker $ wocker wp core download --version=3.5 --force
```

Now, you will have a WordPress 3.5 environment.

I was considering to have options to choose WordPress version when creating containers, but finally I think this is the ideal way of Wocker.

**Comment by ben-barbier** [comment]
Thank you a lot!

It works perfectly.
