### ISSUE TITLE
error SSH-2.0-OpenSSH_6.4 Protocol mismatch

### ISSUE THREAD

**Issue by jastuccio** [wckr/wocker#17]
When I surf to 127.0.0.1:2022 the browser reports the error `SSH-2.0-OpenSSH_6.4 Protocol mismatch` How do I correct this?

**Comment by ixkaito** [comment]
Could you tell me your environment, and did you change some configurations of Wocker?
The default IP of Wocker is `172.17.8.23`, and only port `80` is available at the moment.

**Comment by jastuccio** [comment]
Im on OSX.  Not sure where I got the address `127.0.0.1:2022` from.  I decided to just stick with Vagrant for now and put anything docker related aside so  I deleted the wocker VM.  I wasnt expecting such a fast response or I would have kept the VM around for a few days.
