### ISSUE TITLE
Add documentation about wordpress version selection.

### ISSUE THREAD

**Issue by ben-barbier** [wckr/wocker#18]
Please, could you add your explanation about wordpress version selection (https://github.com/wckr/wocker/issues/16) on documentation site (http://wckr.github.io/) ?

PS: https://github.com/wckr/wocker/issues/16 works fine.

++ !

**Comment by ixkaito** [comment]
Will do :+1:

**Comment by ixkaito** [comment]
Done!
http://wckr.github.io/tips/

**Comment by ben-barbier** [comment]
Great ! :+1:
