### ISSUE TITLE
Error after vagrant up, and old data export (vagrant upでのエラーと、旧データの抜き出し)

### ISSUE THREAD

**Issue by junonet** [wckr/wocker#19]
There's no problem before; however, I got this error when `vagrant up` last Sunday:

```
==> default: Setting hostname...
The following SSH command responded with a non-zero exit status.
Vagrant assumes that this means the command failed!

systemctl start system-cloudinit@-var-tmp-hostname.yml.service

Stdout from the command:

Stderr from the command:

Job for system-cloudinit@-var-tmp-hostname.yml.service failed because a configured resource limit was exceeded. See "systemctl status system-cloudinit@-var-tmp-hostname.yml.service" and "journalctl -xe" for details.
```

The wocker version was v0.5.0, and I reinstalled v0.6.0.

Searched on google:
https://github.com/coreos/bugs/issues/382
I get to the source of this issue but don't know what to do.

Some of my friends also got this error.

It worked well just after reinstalling vagrant and wocker but would have same error.

http://stackoverflow.com/questions/30822566/job-for-system-cloudinit-var-tmp-hostname-yml-service-failed-because-a-configu
This is another source.

$update_channel='stable'
$ vagrant destroy
$ vagrant up

This worked well.
However, `vagrant up` shown the same error next day.

Please tell me what should I do?

ーーーーーーーーーーーーーーーーーーーーーーーーーーーーー

In addítion, when I reinstalled wocker, I moved the old one to wocker_old.
My old data is in wocker_old/data e.g. hoge.
I haven't exported the database to a SQL file like wordpress.sql.

$ vagrant up　# when this worked
$ cd wocker_old
$ vagrant up
$ vagrant ssh
$ wocker start hoge

Got this error:

```
Error response from daemon: No such container: hoge
FATA[0000] Error: failed to start one or more containers
```

wocker_old/data is not synced but wocker/data is.

Is there any way to export the old database.

---

日本語で失礼します。

前日には問題なかったものが
次の日
vagrant upすると

==> default: Setting hostname...
The following SSH command responded with a non-zero exit status.
Vagrant assumes that this means the command failed!

systemctl start system-cloudinit@-var-tmp-hostname.yml.service

Stdout from the command:

Stderr from the command:

Job for system-cloudinit@-var-tmp-hostname.yml.service failed because a configured resource limit was exceeded. See "systemctl status system-cloudinit@-var-tmp-hostname.yml.service" and "journalctl -xe" for details.

というエラーが出るようになりました。
先週の日曜日です。

wockerのバージョンは、v0.5.0で、入れなおしの際は、v0.6.0にしました。

googleで調べていくと
https://github.com/coreos/bugs/issues/382
の記事にたどり着くのですが、どうしていいのかわかりません

この症状は、知人も数名、同様におきています。

vagrantとwocker を入れなおしても、初めはうまくいきますが、また同じようになりました。

http://stackoverflow.com/questions/30822566/job-for-system-cloudinit-var-tmp-hostname-yml-service-failed-because-a-configu
記事もあり、

$update_channel='stable'
$ vagrant destroy
$ vagrant up

すると、うまく動くようになったのですが、
これも、次の日にvagrant upすると、またエラーがでました。

どのように対処していいのか教えていただけたらと思います。

ーーーーーーーーーーーーーーーーーーーーーーーーーーーーー

また、wockerを入れなおす際、元のデータをwocker_oldとしておいています。
wocker_old > data > の中に作業中のものがあるのですが、（仮にhoge）
データをwordpress.sqlのようにexportしていませんでした。

$ vagrant up　がうまくいく時に
$ cd wocker_old
$ vagrant up
$ vagrant ssh
$ wocker start hoge

としても、
Error response from daemon: No such container: hoge
FATA[0000] Error: failed to start one or more containers 

となり、
wocker_old > data 内を見てくれず、
新しく作ったwocker > data > の中を見に行ってしまいます。

exportしてないが、元のデータファイルはある場合、
データを取り出すことはできないのでしょうか？

非常にわかり難い説明で
2点の質問になりますが、よろしくお願いします。

**Comment by ixkaito** [comment]
# First Question

What is displayed when `$ vagrant box list`?

# Second Question

> In addítion, when I reinstalled wocker, I moved the old one to wocker_old...

Wocker is not designed to be installed more than one. Your usage is not ideal.

CoreOS Vagrant uses NFS to synce data. The information of synced folder will be written to the file `/etc/exports` after the first `vagrant up`. You can exec `$ cat /etc/exports` to check it. Therefore, the synced folder won't be changed even though you move the Wocker directory to `wocker_old`.

Here is a solution:

**1. Revert Wocker directory from `wocker_old` to `wocker`**

**2. Start the container you want to export the database of. e.g. `hoge`**

```
$ vagrant up
```

```
$ vagrant ssh
```

```
core@wocker ~ $ wocker start hoge
```

**3. Export the database using `wocker wp` command**

```
core@wocker ~ $ wocker wp db export
```

`wordpress.sql` will be exported to `wocker/data/hoge`.

# Usage of Wocker
- DO NOT `vagrant destroy`.
- Don't install Wocker more than one but create containers using `core@wocker ~ $ wocker run` to manage multiple sites.
- Use `core@wocker ~ $ wocker update` to update Wocker.

---

# 質問1

`$ vagrant box list` でなんと表示されますか？

# 質問2

> また、wockerを入れなおす際、元のデータをwocker_oldとしておいています...

Wocker は複数のインストールを想定して作られていませんので、こちらの運用方法自体あまり理想的ではありません。

CoreOS Vagrant は NFS でデータ同期を行っていますので、一度 `vagrant up` すると、`/etc/exports` というファイルにその同期フォルダの情報が書き込まれます。`$ cat /etc/exports` で確認できます。ですので、Wocker のディレクトリを `wocker_old` に変更しても、同期フォルダは `wocker/data` のままになっています。

解決方法としては、

**1. Wocker ディレクトリを`wocker_old` から `wocker` に戻す**

**2. データベースエクスポートしたいコンテナ `hoge` を立ち上げる**

```
$ vagrant up
```

```
$ vagrant ssh
```

```
core@wocker ~ $ wocker start hoge
```

**3. `wocker wp` コマンドでデータベースをエクスポートする**

```
core@wocker ~ $ wocker wp db export
```

これで `wocker/data/hoge` に `wordpress.sql` がエクスポートされます。

# Wocker の運用について
- `vagrant destroy` をしない
- 複数サイトの運用は Wocker を複数インストールするのではなく、`core@wocker ~ $ wocker run` で複数コンテナを作る
- Wocker のアップデートは `core@wocker ~ $ wocker update` でできます

**Comment by junonet** [comment]
Q1.

```
cent64_minimal_i386 (virtualbox, 0)
coreos-stable       (virtualbox, 607.0.0)
miya0001/vccw       (virtualbox, 2.0.0)
```

This was displayed.

Q2.
I wanted to export the DB to wordpress.sql before I changed the directory from `wocker` to `wocker_old`, but I couldn't because of the error after `vagrant up`.

Now, I revert Wocker directory from `wocker_old` to `wocker` and did this:

```
$ vagrant up
```

However, same error.

```
==> default: Setting hostname...
The following SSH command responded with a non-zero exit status.
Vagrant assumes that this means the command failed!
............
```

---

お返事、翻訳、ありがとうございます。

質問1では、    

```
cent64_minimal_i386 (virtualbox, 0)
coreos-stable       (virtualbox, 607.0.0)
miya0001/vccw       (virtualbox, 2.0.0)
```

となります。

質問2は、
書いて頂いてることをして、
wordpress.sql をエクスポートしたかったのですが、
wocker_old に変更する前に（wockerだった時）
vagrant upで、はじめの症状が出たため、次に進めませんでした。

今も、教えていただいたように
Wocker ディレクトリをwocker_old から wocker に戻し

```
$ vagrant up
```

しましたが、同じように、

```
==> default: Setting hostname...
The following SSH command responded with a non-zero exit status.
Vagrant assumes that this means the command failed!
............
```

となってしまいます。

翻訳のお手間や、お忙しい時なのに申し訳ありません。
時間のあるときにお返事頂ければ幸いです。
よろしくお願いします。

**Comment by ixkaito** [comment]
# Q1.

Please try this in your Wocker directory:

```
$ vagrant box update
```

```
$ vagrant up
```

# Q2.

Did you `vagrant destroy` in your old Wocker?
If you did, you're not able to export the DB anymore.
If you didn't, you will have no problem to export after you solved the error.

---

# 質問1

Wocker ディレクトリでこちらを試してください。

```
$ vagrant box update
```

```
$ vagrant up
```

# 質問2

旧 Wocker で `vagrant destroy` はしてないですよね？
もししている場合は、DB のエクスポートはもう不可能です。
していない場合は上記エラー解決後通常通りでできます。

**Comment by junonet** [comment]
Q1.

```
$ vagrant box update
```

によって、エラーも出なくなりました。
ありがとうございます。

Q2.
旧 Wocker で vagrant destroyしてたので、データはあきらめます。

今後は、気をつけながら運用します。

お忙しい中、どうもありがとうございました。

**Comment by ixkaito** [comment]
:)
