### ISSUE TITLE
Multiple environments?

### ISSUE THREAD

**Issue by ekandreas** [wckr/wocker#2]
How do I initialize multiple environments, eg I need several WP-devs in one Vagrant VM.
I'm missing the point with this if there's only one container per Vagrant.

**Comment by ixkaito** [comment]
You can hold two or more containers in one VM but cannot run them at the same time, so you have to switch between them.

## Here's the steps to switch between containers

### 1. Stop the running container

```
$ wocker stop CONTAINER
```

**Note:** `$ wocker rm CONTAINER` will delete the container and local files synced.

### 2. Run a new container or restart a stopped one

```
$ wocker run [--name CONTAINERNAME]
```

or

```
$ wocker start ANOTHERCONTAINER
```

**Note:** You can list running containers using `$ docker ps` or `$ wocker ps` (alias) and all containers include stopped ones using `$ docker ps -a` or `$ wocker ps -a` (alias).

This issue may also help. #1

**Comment by ekandreas** [comment]
Ahh, ok, not two at the same time?

**Comment by ekandreas** [comment]
But I think I know how to simplify the switch without entering vagrant ssh.

**Comment by ixkaito** [comment]
No, not two and more at the same time.

Really? How do you simplify the switch without vagrant ssh?
