### ISSUE TITLE
Location of php.ini

### ISSUE THREAD

**Issue by axelson** [wckr/wocker#20]
This might be exposing my ignorance about docker but where can I find and edit the php.ini configuration file? I need to edit the `upload_max_filesize` setting.

**Comment by ixkaito** [comment]
Will increase `upload_max_filesize` in the next version.

**Comment by ixkaito** [comment]
`upload_max_filesize` was increased to 32M in v0.7.0. Please `vagrant up` and `vagrant ssh` then:

```
core@wocker ~ $ wocker update
```

Please note that your existing containers will not be updated. If you want to edit php.ini of them, here's the procedure:

**1. Start your existing container e.g. `my_container`**

```
core@wocker ~ $ wocker start my_container
```

**2. Get into the container**

```
core@wocker ~ $ wocker exec -it my_container bash
```

**3. Edit php.ini using vi editor**

```
root@****:/var/www/wordpress# vi /etc/php5/apache2/php.ini
```
