### ISSUE TITLE
Symlinks to themes not working

### ISSUE THREAD

**Issue by kiddhustle** [wckr/wocker#21]
Hi there

I recently tried symlink-ing to some themes located in the local 'data' directory, from the wp-content/themes directory, however these themes are not showing from within the WP admin.

I'm wondering if I need to configure the Apache service from within the container to following symlinks?

I'm not sure where the Apache host configs are located within the coreos box. Could someone point me in the right direction so that I can troubleshoot?

I created the symlinks for each of the themes I wish to develop like so:
1. cd into 'data' directory: `cd data`
2. cp -R themes directory in the current 'data' directory (named wordpressthemes): `cp -R ../pathtothemedirectory wp-content/themes`
3. cd into themes directory: `cd wp-content/themes`
4. create symlink for each theme: `ln -s ../../wordpressthemes/themename themename`

**Comment by ixkaito** [comment]
Files and folders directly in the local 'data' directory besides the folder for running container will not be mounted. They are synced with CoreOS but will NOT be mounted by Docker container. Only files in each container folder (usually same as container name) will be mounted.

The following steps will work:

**1. Run a new container named 'myproject'**

```
core@wocker ~ $ wocker run --name myproject
```

**2. Copy your 'wordpressthemes' into 'myproject' in your local machine**

```
$ cd data
$ cp -R /PATHTO/wordpressthemes myproject
```

**3. `cd` into themes directory**

```
cd myproject/wp-content/themes
```

**4. Create symlink for each theme**

```
ln -s ../../wordpressthemes/themename themename
```

However, I can't see any advantage in this style.
