### ISSUE TITLE
wp commands not working | /usr/local/bin read only file system

### ISSUE THREAD

**Issue by kiddhustle** [wckr/wocker#22]
After running the `wocker run` / `wocker start wocker` command The `wp` wordpress shell commands don't work.

I checked the Docker file for how the plugin is installed and tried installing it manually but after downloading the wp-cli.phar file I can't move the file to the desired location. This is the error message:

mv: inter-device move failed: 'bin/wp-cli.phar' to '/usr/local/bin/wp-cli.phar'; unable to remove target: Read-only file system

**Comment by ixkaito** [comment]
`wocker` command is not available for `wp shell` now. I will improve this.
For now, you can use `exec` to use `wp shell` command.

```
core@wocker ~ $ wocker exec -it CONTAINER wp --allow-root shell
wp>
```

**Comment by kiddhustle** [comment]
OK thanks that does the trick

**Comment by ixkaito** [comment]
I fixed this.
http://wckr.github.io/changelog/

Please `wocker update` to use `wocker wp shell` command.

**Comment by franz-josef-kaiser** [comment]
@ixkaito That should absolutely be part of the docs.

**Comment by ixkaito** [comment]
@franz-josef-kaiser Do you mean `wocker wp` or `wocker wp shell`?

**Comment by franz-josef-kaiser** [comment]
@ixkaito Both :)

**Comment by ixkaito** [comment]
They are on the docs. http://wckr.github.io/commands/#h3-8
