### ISSUE TITLE
Wocker hangs on Windows 10

### ISSUE THREAD

**Issue by esalexreyes** [wckr/wocker#23]
Tried several times trying to install it, it always hangs on the last step: 
`wocker run --name wocker`
No error is shown, I can leave my computer on and running for hours and the step never completes.
I can vagrant ssh from another shell.
Also I never got the ip or the web address working.

**Comment by ixkaito** [comment]
Sorry for the inconvenience. NFS synced folder is likely to have problems with all Mac, Windows, and Ubuntu. I'm planning to stop using CoreOS at the next major version. It might also solve this problem. Please also see #14.

**Comment by ixkaito** [comment]
Wocker 1.0.0 is now available. http://wckr.github.io/
Please have a try on Windows. You may have to launch the shell application as an admin to run Wocker.

**Comment by esalexreyes** [comment]
I just tried it. I'm running it as an admin and I get the following error:

Vagrant attempted to execute the capability 'change_host_name'
on the detect guest OS 'linux', but the guest doesn't
support that capability. This capability is required for your
configuration of Vagrant. Please either reconfigure Vagrant to
avoid this capability or fix the issue by creating the capability.

**Comment by esalexreyes** [comment]
Also this may help, if I run a provision after the above error I get this one

```
==> wocker: lstat /home/docker/data: no such file or directory
The SSH command responded with a non-zero exit status. Vagrant
assumes that this means the command failed. The output for this command
should be in the log above. Please read the output to determine what
went wrong.
```

**Comment by ixkaito** [comment]
Could you give me your version information of OS, Vagrant, and VirtualBox?

**Comment by esalexreyes** [comment]
Sorry for the late reply! It seems updating Virtual Box and Vagrant did the trick for me. 
My Current version: Windows 10, Vagrant version 1.8.1, VirtualBox 5.0.10
Thanks for the hard work! Wocker rocks!

**Comment by ixkaito** [comment]
Glad to hear that! Does everything works well?

**Comment by esalexreyes** [comment]
Yep, everything is working properly now. :+1:

**Comment by ixkaito** [comment]
:smile:
