### ISSUE TITLE
Update to Wordpress 4.4 ?

### ISSUE THREAD

**Issue by arieltoledo** [wckr/wocker#24]
Hi any chance to update to wordpress 4.4 ?

**Comment by ixkaito** [comment]
Yes, I'm planning to do it. Maybe before the new year.

**Comment by colin-johnston** [comment]
+1

Updating to 4.4 in UI works fine, but running `wocker wp core update` hangs for some reason.

Really enjoyed my test-run of Wocker today; really quick setup and a pleasure to use.

**Comment by ixkaito** [comment]
Thanks @electronspin !
I recognized the `wocker wp core update` problem.
I'm working on the next major version. It will be 4.4, and I think it will also solve the problem.

**Comment by ixkaito** [comment]
Wocker 1.0.0 is now available! 
https://github.com/wckr/wocker/releases/tag/v1.0.0

Changelog:
http://wckr.github.io/changelog/

Please note: `wocker update` command does NOT upgrade v0.x to v1.0.0 or later. Please clone the repository again. But, it updates to WordPress 4.4 on Wocker v0.x.

`wocker wp core update` also works well on v1.0.0. Please have a try.
