### ISSUE TITLE
vagrant-hostsupdater doesn't create new Wocker Container Hosts Entries

### ISSUE THREAD

**Issue by GForceWeb** [wckr/wocker#29]
Title pretty much sais it all, when running wocker run --name newcontainer hosts entries don't appear to automatically be added.

**Comment by ixkaito** [comment]
`wocker run` doesn't create new IP and hostname. The hostname (URL) is always "wocker.dev".

Please just open "wocker.dev" on your browser after `wocker run`.
If you want to use an older container, please `wocker stop` and `wocker start OLDCONTAINER`.

**Comment by ixkaito** [comment]
Please also see: #32
