### ISSUE TITLE
Files served from wrong directory.

### ISSUE THREAD

**Issue by robskidmore** [wckr/wocker#3]
I created a new container called test and stopped the original one created by wocker.

When I run `wocker ps` it shows that I am running the test container.

However when I visit http://wocker.dev the files from the original wocker container are still being served.

Any changes I make to files within the test container are not showing up in the browser. In fact I can delete the entire wordpress installation with out any change.

Did I miss some step along the way?

**Comment by ixkaito** [comment]
Did you create a new container before stopping the original one?
You have to stop the running container before creating or starting another.

If you stop a container, the name of the directory will be changed from `wordpress` to `ID_CONTAINERNAME`, and you can find them in your local `data` directory.

After you stop a container, if you enter `$ wocker run --name test`, a new `wordpress` directory and container will be created. Make change here. Again, `$ wocker stop test` will move `wordpress` directory to `ID_test`.

When you restart a container using a Wocker command e.g. `$ wocker start test`, `ID_test` will be taken back to `wordpress`.

**Comment by robskidmore** [comment]
Okay got it. When I create a container it is named `ID_CONTAINERNAME` when I run that container the directory is changed to `wordpress`

So the current live directory will always be named `wordpress`. Then when I stop a container it reverts back to its `ID_CONTAINERNAME`

It all makes sense.

**Comment by ixkaito** [comment]
Exactly.
