### ISSUE TITLE
Any plans on shipping with PHP7?

### ISSUE THREAD

**Issue by alainux** [wckr/wocker#31]
The title says it all

**Comment by ixkaito** [comment]
Yes, but maybe I will add an option to use PHP7 at first.
Something like `$ wocker run wocker/wocker:php7`.

**Comment by matthewlilley** [comment]
Any news on this?

**Comment by ixkaito** [comment]
@matthewlilley I'm planning a major update. It includes many new features, and it takes a long time. Sorry about this.

**Comment by matthewlilley** [comment]
Thanks for the update @ixkaito. Really enjoy using wocker, but stepped away for a while because of the lack of PHP 7 support... It's great to hear you're working on this, and thanks!

**Comment by ixkaito** [comment]
[V1.2](https://wckr.github.io/changelog/) is now using PHP 7.
