### ISSUE TITLE
PHP error log location

### ISSUE THREAD

**Issue by kiddhustle** [wckr/wocker#33]
Hi there

Could you point me in the direction of the PHP error logs, or give a direction that is good for them to be configured in the php.ini file to be written to? I've tried settings them to be written to the /var/log directory but I see a message saying that the file system type is unrecognized whenever I try to read from it with tail:

Message:

tail: unrecognized file system type 0x794c7630 for '/var/log/php/errors.log'. please report this to bug-coreutils@gnu.org. reverting to polling

**Comment by ixkaito** [comment]
Hi,

You can set `error_log` in .htaccess. Please try to put this line `php_value error_log /var/www/wordpress/errors.log` in your .htaccess. This will create errors.log in the shared container directory. You can change `/var/www/wordpress/errors.log` wherever you want.
