### ISSUE TITLE
integrating wocker in a node-gulp-bower worflow

### ISSUE THREAD

**Issue by fnicastri** [wckr/wocker#35]
Hi Kite,
I was thinking of integrating wocker in my workflow which already
includes node,gulp,bower,bootstrap and _s and I was thinking to install
these tools in the vagrant vm so this can be more portable.
Can you suggest the best way to do this?

Thanks for the answer

Francesco

**Comment by ixkaito** [comment]
Hi Francesco,

Thank you for using Wocker.

Are you familiar with Docker? If yes, you can create your own Wocker image. Here's the default Wocker image: https://github.com/wckr/wocker-dockerfile. Once you create your own Wocker image, you can run it like this: `wocker run --name CONTAINER MYWOCKERIMAGE`.

Here's another approach. I think it's not necessary to include Node and Gulp in the Wocker image. I have a WordPress starter theme project for Gulp: https://github.com/wp-bathe/bathe. I download it into the theme directory and run Gulp on my local machine. Hope this helps.

**Comment by fnicastri** [comment]
Hi Kite,

thank you for your reply.
Sorry for the late but is a busy period at work.

I was thinking of installing them directly in the vm
because it will be simpler in a multiplatform scenario.
When I'm in the Office I have a little linux server and I've no problems to
install and run all the tools.
But on the road I'm on Windows (I chose this after 10 years of OS X)
and it will be simpler to have all the tools directly in the vagrant VM
and enjoy the consistency that provides ;-)
Maybe I'm wrong, I'm not so familiar with docker and vagrant.

What do you think?

Thanks,
Francesco

**Comment by ixkaito** [comment]
Sorry for the late reply.

Actually, the Vagrant VM of Wocker is just a Docker engine. You will have to install Node.js, Gulp, and Bower into the Docker image not the VM.

Do you use Node.js for other projects on your local Windows? If so, I recommend you to install and run it on the local machine. If you only use Node.js on Wocker, installing necessary packages into the Docker image may simplify your workflow. However, you will have to run Node or npm commands on the Docker container every time like this:
1. `$ vagrant ssh`
2. `wocker ~ $ wocker exec -u wocker -it CONTAINER bash`
3. `wocker@****:/var/www/wordpress$ node` or `wocker@****:/var/www/wordpress$ npm`

**Comment by fnicastri** [comment]
Thank you Kite.
