### ISSUE TITLE
Apache config variable not defined

### ISSUE THREAD

**Issue by franz-josef-kaiser** [wckr/wocker#36]
The `/etc/apache2/apache2.conf` has a bunch of undefined variables. Those need to get set.

``` bash
$ docker exec -it wocker /usr/sbin/apache2                                                                                                                                                                           

[Tue Apr 12 06:54:32.327474 2016] [core:warn] [pid 457] AH00111: Config variable ${APACHE_LOCK_DIR} is not defined
[Tue Apr 12 06:54:32.327546 2016] [core:warn] [pid 457] AH00111: Config variable ${APACHE_PID_FILE} is not defined
[Tue Apr 12 06:54:32.327736 2016] [core:warn] [pid 457] AH00111: Config variable ${APACHE_RUN_USER} is not defined
[Tue Apr 12 06:54:32.327793 2016] [core:warn] [pid 457] AH00111: Config variable ${APACHE_RUN_GROUP} is not defined
[Tue Apr 12 06:54:32.327845 2016] [core:warn] [pid 457] AH00111: Config variable ${APACHE_LOG_DIR} is not defined
[Tue Apr 12 06:54:32.339578 2016] [core:warn] [pid 457] AH00111: Config variable ${APACHE_LOG_DIR} is not defined
[Tue Apr 12 06:54:32.339736 2016] [core:warn] [pid 457] AH00111: Config variable ${APACHE_LOG_DIR} is not defined
[Tue Apr 12 06:54:32.339934 2016] [core:warn] [pid 457] AH00111: Config variable ${APACHE_LOG_DIR} is not defined
AH00526: Syntax error on line 74 of /etc/apache2/apache2.conf:
Invalid Mutex directory in argument file:${APACHE_LOCK_DIR}
```

Above error makes it impossible to use the binary to restart Apache for e.g.:

```
$ docker exec -it wocker /usr/sbin/apache2 -k restart
… above errors here …
```

**Comment by ixkaito** [comment]
Hi,

In Ubuntu/Debian, you should use the `service` command to control Apache:

```
$ wocker exec CONTAINER service apache2 restart
```

It might be a warning about the "ServerName" but not really a problem (as in that something does not work). I'm considering to fix this issue.

**Comment by franz-josef-kaiser** [comment]
@ixkaito Thanks. Will try that. Question: Where exactly are those variables then set?

**Comment by ixkaito** [comment]
Default variables are set in `/etc/apache2/envvars` which are not available if apache2 is started directly.

**Comment by franz-josef-kaiser** [comment]
That kept complaining about the `Servername` not being set. But as I have no idea how to `sed` (or whatever) to map a dynamically generated IP into it, I'll just close this issue. Thanks.

**Comment by ixkaito** [comment]
I fixed the `ServerName` issue. After `wocker update` and creating a new container, you will be able to restart Apache without warning.

**Comment by franz-josef-kaiser** [comment]
Thanks. [Reference to commit](https://github.com/wckr/wordpress-dockerfile/commit/2b250af738456889e3cbb164f5eac385dec3d552) for later readers.
