### ISSUE TITLE
Can't activate Timber plugin

### ISSUE THREAD

**Issue by jastuccio** [wckr/wocker#38]
EDIT:  When I install the plugin using composer it will not activate.  When I install it through WordPress it works.  There must be something going on with my composer.json.  That is not a Wocker issue though. Please close this non-issue.

---

This morning I tried to install the [Timber plugin](http://upstatement.com/timber/) through Wordpress.  It gave me an error:

`Plugin could not be activated because it triggered a fatal error.
Fatal error: Class 'Timber' not found in /var/www/wordpress/wp-content/plugins/timber/timber.php on line 26`

Next I spun up a new Wocker container.  It gave me the same error. I was then able to activate the plugin on a site on my server without errors.

Let me know if there are any logs or information I can provide that might be helpful.

**Comment by ixkaito** [comment]
Anyway, thanks for letting me know. I also try Timber, and it works well without any errors :)
