### ISSUE TITLE
Multisite support?

### ISSUE THREAD

**Issue by VesterDe** [wckr/wocker#39]
Hey, I seem to be getting ERR_ICANN_NAME_COLLISION after setting up Multisite on a page inside Wocker.

I used subdomains at multisite setup, would it have helped if I used subdirectories?

**Comment by VesterDe** [comment]
Ok, I felt bad for writing the issue without trying subdirectories as well, so I did.

It works with subdirectories, but was a bit wonky with login. It kept redirecting me back to login and didn't let me get to my admin panel.

What fixed it was to set SUBDOMAIN_INSTALL to true, temporarily, in wp-config.php. This let me login, then I could set it back to false, and now it just works.

**Comment by ixkaito** [comment]
Thanks for letting me know. In my case, I didn't need to set `SUBDOMAIN_INSTALL` to `true`. Maybe the steps are different. I recommend you to set the permalinks to structures other than the default to generate a `.htaccess` file before enabling multisite.

**Comment by VesterDe** [comment]
I'm not sure it works 100% for me, but I won't track the bug crazily unless it shows itself more often. I believe it's ok for now. 
Thanks for the input :)
