### ISSUE TITLE
Ubuntu needs nfs-kernel-server installed

### ISSUE THREAD

**Issue by m-e-h** [wckr/wocker#4]
Just wanted to point this out in case anyone else got this message on Linux:

```
It appears your machine doesn't support NFS, or there is not an adapter to enable 
NFS on this machine for Vagrant.
```

They'll need to:

```
apt-get install nfs-kernel-server
```

This is probably just a dependency thing for Ubuntu, even though I've been running VVV without the error...
Maybe just something to add to the documentation for Linux users.

Here's the original Vagrant issue:
https://github.com/mitchellh/vagrant/issues/1534/#issuecomment-34242441

**Comment by ixkaito** [comment]
Thanks.
I added this issue to the documentation.
[http://wckr.github.io/](http://wckr.github.io/)
