### ISSUE TITLE
Wocker gives a 404 after some time

### ISSUE THREAD

**Issue by joeynimu** [wckr/wocker#46]
Hi,

First and foremost i want to say thank you this tool that eases wp development.

I am experiencing this issues whereby after i start a container and visit http://wocker.dev it works as expected. But after a few minutes when i try to reload the page or as i go about in interacting with the website, i get a 404. Please see the attached screenshot. When i check if the container is still running on terminal it turns out it's still running. weird.
What could be the issue? Thanks
<img width="633" alt="screen shot 2016-08-10 at 21 23 04" src="https://cloud.githubusercontent.com/assets/1195863/17565581/af35570a-5f40-11e6-888c-249a403cb3ed.png">

**Comment by ixkaito** [comment]
Hi @joeynimu 

First, chould you tell me what OS you are using, Mac, Windows, or Ubuntu and check if there is a line `10.0.23.16  wocker.dev` in your `hosts` file?

Then, could you try the following and tell me what happens if you visit http://wocker.dev after each one:
- Stop and restart the container
  
  ```
  wocker ~ $ wocker stop && wocker start CONTAINER
  ```
- Reload Vagrant
  
  ```
  $ vagrant reload
  $ vagrant ssh
  wocker ~ $ wocker start CONTAINER
  ```
- Go to http://wocker.dev/wp-admin/options-permalink.php and just press "Save Changes" button
- Change the permalink setting to other than "Plain"
- Stop the container and recreate one
  
  ```
  wocker ~ $ wocker stop && wocker run --name test
  ```

**Comment by joeynimu** [comment]
Hi @ixkaito I am using Mac OS X Yosemite version 10.10.5.

I have checked my host file and found that there is indeed this line with the IP 10.0.23.16
`config.vm.hostname = "wocker.dev"
  config.vm.network :private_network, ip: "10.0.23.16"`
- When i stop and restart the container i get a 404 as in the previous screenshot.
- When i reload vagrant the site come backup but for a few minutes after which i get a 404 on page reload. But after trying a couple of reloads, it came back up again.
- I went to permalinks settings and hit save
- Changed the permalink setting to other than plain
- Stopped and created a new container. Which seems to be accessible just fine but after sometime i get 'the site can't be reached' message as seen in the screenshot. Checking if the container is running, it still does. Really weird
  <img width="1252" alt="screen shot 2016-08-11 at 10 14 38" src="https://cloud.githubusercontent.com/assets/1195863/17581183/99639e8e-5fac-11e6-9a37-0a2525673b68.png">

vagrant version is 1.8.1 let me try to upgrade and see if that fixes it.

**Comment by joeynimu** [comment]
I have upgraded my vagrant and my box still experiencing the same problem. Really frustrating and the way i was hyped about this tool :-(

**Comment by ixkaito** [comment]
@joeynimu 

Yes, it seems a little weird. Is your network changing while Wocker is running?

By the way, the `hosts` file is at `/etc/hosts`, so after you get 404, could you check whether there is `10.0.23.16 wocker.dev` in it and whether your network changed?

```
$ cat /etc/hosts
```

**Comment by joeynimu** [comment]
@ixkaito i think i have solved it by simply rebooting my machine. It seems to work as expected and i can do `$ wocker stop && start CONTAINER`

Thanks for your time and apologise for bothering you with this. I should have tried to restart my machine initially.

Thanks a bunch for the awesome tool, cheers 👍
