### ISSUE TITLE
wocker wp cli update

### ISSUE THREAD

**Issue by kitakado-h** [wckr/wocker#48]
When attempting to update WP-CLI,I get an error.

Error message  
“Error: /usr/local/bin/wp is not writable by current user”

**Comment by ixkaito** [comment]
@kitakado-h 

Could you tell me your Wocker version?

To check it, please run: 

```
wocker ~ $ wocker -v
```

**Comment by kitakado-h** [comment]
Hi @ixkaito

I am using wocker version 1.1.3.
WP-CLI version: 0.24.0-alpha-28eed6b

In the case of a container made with wocker version 1.1.2.
WP-CLI version: 0.22.0-alpha-1267f2c

**Comment by ixkaito** [comment]
@kitakado-h 

I see. You have no problem of WP-CLI on version 1.1.3, but you can't use WP-CLI on your old containers created from version 1.1.2, right?

It's a little tricky to update WP-CLI. Please try the following steps:
1. Start your container
   
   ```
   wocker ~ $ wocker start CONTAINER
   ```
2. Start a bash session in the container
   
   ```
   wocker ~ $ wocker exec -it CONTAINER bash
   ```
3. Update WP-CLI
   
   ```
   root@****:/var/www/wordpress# wp cli update --allow-root
   ```
4. Type `y` then push `enter`

That's it!

**Comment by kitakado-h** [comment]
@ixkaito 

That did the trick! Thank you!
