### ISSUE TITLE
Vagrant up does not complete

### ISSUE THREAD

**Issue by MartyThornley** [wckr/wocker#5]
I keep getting this same result:

==> default: Importing base box 'coreos-stable'...
==> default: Matching MAC address for NAT networking...
==> default: Checking if box 'coreos-stable' is up to date...
==> default: Setting the name of the VM: wocker_default_1425759203312_83581
==> default: Destroying VM and associated drives...
/opt/vagrant/embedded/gems/gems/vagrant-1.7.2/plugins/hosts/bsd/cap/nfs.rb:139:in `read': Is a directory - /etc/exports (Errno::EISDIR)
    from /opt/vagrant/embedded/gems/gems/vagrant-1.7.2/plugins/hosts/bsd/cap/nfs.rb:139:in`nfs_prune'
    from /opt/vagrant/embedded/gems/gems/vagrant-1.7.2/lib/vagrant/capability_host.rb:111:in `call'

And then a list of maybe 100 more in the same fashion.  from /opt/vagrant.....

I am on a Mac 10.9.5, have vagrant and virtual box installed. 

Any ideas?

**Comment by ixkaito** [comment]
"/etc/exports" is usually a file on Mac OS X. I don't know why "/etc/exports" is a directory for you.
If it is not necessary and is empty, try this:

```
$ sudo rm /etc/exports
```

```
$ sudo touch /etc/exports
```

Then, try `$ vagratn up` again.
