### ISSUE TITLE
Why docker + vagrant?

### ISSUE THREAD

**Issue by step21** [wckr/wocker#50]
Hej, so I was looking into using docker for development to replace my VVV setup - which uses vagrant to set up wordpress dev sites.
Mainly, the idea was that docker (at least on unixes) has much lower overhead. For this wocker seemed perfect, but then it seems you always use vagrant (which uses a vm) and then run docker inside of that.
Why is that? Would it also be possible to set up wocker without vagrant?

**Comment by ixkaito** [comment]
@step21 

Thanks for trying Wocker.
Please see #47.

> Would it also be possible to set up wocker without vagrant?

I'm planning to do this. Kitematic or Docker for Mac/Windows.

**Comment by step21** [comment]
Thanks. Sorry that I didn't find that, forgot to check closed issues.

**Comment by ixkaito** [comment]
@step21 It's OK. Feel free to open issues :)
