### ISSUE TITLE
Running Wocker without Vagrant?

### ISSUE THREAD

**Issue by khromov** [wckr/wocker#52]
Any way to run Wocker without Vagrant? Currently using the latest Docker Engine which has support for Hyper-V on Windows, it's a much better way to run docker containers than have an intermediary virtual machine.

 https://docs.docker.com/engine/installation/

**Comment by ixkaito** [comment]
@khromov 

Yes, it's better to use the native-like Docker, and I'm planning to get rid of Vagrant, but I have to solve several issues before it.

Here are some reasons of using Vagrant: #47.

Thanks :)
