### ISSUE TITLE
Update to ailispaw barge 2.3.0 prevents wocker from running

### ISSUE THREAD

**Issue by sthag** [wckr/wocker#53]
After updating the box ailispaw barge to the current version 2.3.0 I'm not able to start wocker anymore.

I see this error:
```
There was an error loading a Vagrantfile. The file being loaded
and the error message are shown below. This is usually caused by
a syntax error.

Path: C:/Users/sthag/.vagrant.d/boxes/ailispaw-VAGRANTSLASH-barge/2.3.0/virtualbox/Vagrantfile
Line number: 0
Message: TypeError: no implicit conversion of Pathname into String
```
I got this the first time after executing `vagrant box update`. Afterwards I had two versions of barge. 2.3 and the old 2.2.7.2 which was running as expected before.
If version 2.3 is installed every vagrant command according to wocker shows the error above.
During troubleshooting I uninstalled both barge boxes.
I also removed my wocker directory.
I tried to install from scratch but again I get the error as described:

``` powershell
PS D:\machines\wocker> vagrant up
Bringing machine 'wocker' up with 'virtualbox' provider...
==> wocker: Box 'ailispaw/barge' could not be found. Attempting to find and install...
    wocker: Box Provider: virtualbox
    wocker: Box Version: >= 0
==> wocker: Loading metadata for box 'ailispaw/barge'
    wocker: URL: https://atlas.hashicorp.com/ailispaw/barge
==> wocker: Adding box 'ailispaw/barge' (v2.3.0) for provider: virtualbox
    wocker: Downloading: https://atlas.hashicorp.com/ailispaw/boxes/barge/versions/2.3.0/providers/virtualbox.box
    wocker: Progress: 100% (Rate: 828k/s, Estimated time remaining: --:--:--)
==> wocker: Successfully added box 'ailispaw/barge' (v2.3.0) for 'virtualbox'!
There was an error loading a Vagrantfile. The file being loaded
and the error message are shown below. This is usually caused by
a syntax error.

Path: C:/Users/sthag/.vagrant.d/boxes/ailispaw-VAGRANTSLASH-barge/2.3.0/virtualbox/Vagrantfile
Line number: 0
Message: TypeError: no implicit conversion of Pathname into String
```

I'm using Vagrant 1.8.7, VirtualBox 5.1.10 on Windows 10

**Comment by ailispaw** [comment]
Hi @sthag ,

Thank you for letting me know the issue.
I will check it out.
Could you modify your Vagrantfile like the following  to use barge v2.2.7.2 for a while?

```
  config.vm.box = "ailispaw/barge"
  config.vm.box_version = "2.2.7.2"
```

Best regards.

**Comment by ailispaw** [comment]
I can reproduce this issue and found the cause. I will fix it and release it right away.
Thanks.

**Comment by ailispaw** [comment]
Hi @sthag,

Just released `ailispaw/barge` v2.3.0.1.
Please update the box and try it.
NOTE: Don't forget to remove the line `config.vm.box_version = "2.2.7.2"` before update, if you modified your Vagrantfile for the workaround.

Sorry for this inconvenience and thank you for reporting this again.

**Comment by sthag** [comment]
It is working ... IT IS WORKING :)
Thank you very much for your immediate reaction. This way I can be productive again, lol.

Very nice to have this tool, by the way.

**Comment by ailispaw** [comment]
Thank you for using Wocker and Barge, btw. 😄
