### ISSUE TITLE
Features of creating images from Wocker container and pushing them to Docker Hub

### ISSUE THREAD

**Issue by echizenyayota** [wckr/wocker#54]
もし機会がございましたら、下記の機能改良についてご検討をいただければ幸いです。

【要望の主旨】

Wockerのコンテナをイメージ化して、Docker Hubにプッシュできる機能を付加してほしい。
イメージ的には添付の画像のようになればいいなと考えています。

【補足】

いま、「歯科医院専門」など特定業種用の有料テーマ販売を考えています。
そのとき主に開発するのはテーマとなりますが、そのテーマに合わせてダミーの投稿記事の保持や管理画面の設定など、WordPressシステム全体の調整が必要となります。その場合、GitHubを使ってソースコードの管理をするだけでは用が足りません。

手前味噌で恐縮ですが、以下の記事のように、Wockerのコンテナを絶えず引っ越しさせるという手もあります。
http://blog.ecoteki.com/webservice/post-2610/

ですがそれをすると、

・クライアントPCが壊れたとき、バックアップできていない
・クライアントPCの容量を圧迫する

という懸念が生じます。
またブログ記事で書いているような、コマンド操作をするよりも、DockerまたはWockerコマンドを使って、Docker Hubに登録してしまった方が、作業の手数も減るような感じもします。

手元のクライアントPCで手軽にWordPressテーマを開発できるというのが、Wockerの主旨であるとは思いますが、上記の【要望の主旨】にある機能もあれば、より便利になるかと思います。

もしおてすきのときにでも、機能の付加をご検討いただければ幸いです。
以上、よろしくお願い申し上げます。

【参考サイト】
http://dotinstall.com/lessons/basic_docker/27704
http://dotinstall.com/lessons/basic_docker/27711

![2](https://cloud.githubusercontent.com/assets/8636269/21125299/f00c8782-c127-11e6-8741-84df0734f716.png)

**Comment by ailispaw** [comment]
@echizenyayota との Twitter での会話の後、ちょっと思いついたので、試作してみました。

# Wocker のコンテナをイメージにパッケージングしてポータブルにするツール
https://gist.github.com/ailispaw/1e8f87f0a0def8e09351479d5adc1492

## 使い方

```
wocker ~ $ wget https://gist.githubusercontent.com/ailispaw/1e8f87f0a0def8e09351479d5adc1492/raw/package.sh
wocker ~ $ chmod +x package.sh
wocker ~ $ ./package.sh <イメージ化したいコンテナ名> <イメージ名>
```

例えば：`wocker` という名のコンテナを `ailispaw/wocker` という名のイメージにパッケージングする場合、
```
wocker ~ $ ./package.sh wocker ailispaw/wocker
wocker ~ $ docker images
REPOSITORY          TAG                 IMAGE ID            CREATED             SIZE
ailispaw/wocker     latest              b6289c16540e        43 minutes ago      457.8 MB
wocker/wocker       latest              b25801588468        3 months ago        488.6 MB
```

## パッケージしたイメージを使った起動

```
wocker ~ $ docker run -d --name <新しいコンテナ名> -p 80:80 -p 3306:3306 <イメージ名>
wocker ~ $ docker run -d --name wocker2 -p 80:80 -p 3306:3306 ailispaw/wocker
wocker ~ $ wocker ps
CONTAINER ID        IMAGE               COMMAND                  CREATED             STATUS              PORTS                                        NAMES
04fede03f954        ailispaw/wocker     "/usr/bin/supervisord"   4 seconds ago       Up 3 seconds        0.0.0.0:80->80/tcp, 0.0.0.0:3306->3306/tcp   wocker2
```

## 注意点
ちょっと Wocker の本来の使い方とは異なりますが、これで、イメージをどこへ持っていっても、同じ設定のまま起動させることが出来ます。
ただし、注意しないと行けないのは、イメージの中に全ての環境、設定、WordPressのファイル、テーマ等を埋め込んでいるので、ローカルの開発環境の変更は反映されません。
その時点でのバックアップと同じ効果になります。
ローカルの変更を反映させるには、同じように再度、パッケージングを実行してイメージを作り直す必要があります。

既存のコンテナを破壊することは無いと思いますが、docker 自体の仕組みや使い方を知っていないと使いづらいかも知れません。

@ixkaito 
Wocker の拡張の参考になれば幸いです。

**Comment by echizenyayota** [comment]
@ailispaw さん。
さっそくのコメント、アドバイス、コマンドライン操作ありがとうございます！
まずは、ドットインストールのDocker入門 (全11回)を復習してから、
コマンドを試してみたいと思います。後日、改めてコメントいたします。
http://dotinstall.com/lessons/basic_docker

**Comment by ailispaw** [comment]
スピードアップとイメージの効率化の為にスクリプトを更新しました。
`docker export + docker build` から `docker commit + docker build` に変更しました。

**Comment by ailispaw** [comment]
バグを発見しました。

WordPress フォルダ以下のオーナーが root になっていました。
修正完了しました。

**Comment by ailispaw** [comment]
自分で使ってみた感想ですが、その時点のもので凍結出来るということはバックアップにもなりますし、
第３者（顧客？）に見せたり共有／提出する場合にイメージを渡すだけで、Docker が使えればどこでも見れるのは良いのではないかと思いました。Wocker すら要らない環境でも簡単に作成したテーマ／データが見れますね。

**Comment by echizenyayota** [comment]
@ailispawさん

>パッケージしたイメージを使った起動

ばっちり行けました！ありがとうございます。

---

@ailispawさん。 @ixkaitoさん。
パッケージしたイメージからDocker Hubにイメージをプッシュする方法、またプルをして元のWocker環境に戻す方法が分かったので、追記いたします。

## Docker Hubにイメージをプッシュするコマンド

wocker ~ $ docker login
Username:echizenya
Password:
Email:hoge＠gmail.com

wocker ~ $ docker push echizenya/sakuraclub_image

画像も添付しておきます。

## Docker Hubのイメージを元のWocker環境にプルする方法

 wocker ~ $ docker pull echizenya/sakuraclub_image

## 注意点

**1.**
ログインの際に入力するUsername、Password、Passwordは[Docker Hub](https://hub.docker.com/)にサインアップしたときと同じものを使うこと

**2.**

./package.sh  echizenya/sakuraclub

でコンテナをパッケージするときにイメージ名の前半部分とUsernameが一致しないと、プッシュできません。従ってUsernameとパッケージ名の一部を合わせる必要があります。
（自分の場合Usernameがechizenyaなので、イメージ名はechizenya/hogeとしなければなりません）

**3.**
Docker Hubの個別のイメージ名のところを見ると、**public**となっています。これを**close**にする方法はまだ分かっていません。その方法がわかるまで、Docker Hubにプッシュするのは、ダミーデータしか入っていないWordPressにとどめておいた方が良いと思います。

参考ページ
http://dotinstall.com/lessons/basic_docker/27711

<img width="852" alt="1" src="https://cloud.githubusercontent.com/assets/8636269/21290738/33a3b6d4-c509-11e6-999b-9033438cde4c.png">
<img width="1272" alt="2" src="https://cloud.githubusercontent.com/assets/8636269/21290739/3bd3f7d8-c509-11e6-89b9-7fa71ce73472.png">

---

以上、よろしくお願い申し上げます。

**Comment by echizenyayota** [comment]
あ、publicをprivateにする方法が分かりました。ご覧の通りです↓
https://hub.docker.com/account/billing-plans/

**Comment by ixkaito** [comment]
This feature has been added to [v1.2](https://wckr.github.io/changelog/).
