### ISSUE TITLE
The box 'ailispaw/barge' could not be found 

### ISSUE THREAD

**Issue by riskiii** [wckr/wocker#56]
I get the following error message when I run vagrant up, even when I do a vagrant login:

The box 'ailispaw/barge' could not be found or
could not be accessed in the remote catalog. If this is a private
box on HashiCorp's Atlas, please verify you're logged in via
`vagrant login`. Also, please double-check the name. The expanded
URL and error message are shown below:

URL: ["https://atlas.hashicorp.com/ailispaw/barge"]
Error:

**Comment by ailispaw** [comment]
Hi @riskiii ,

Which version of Vagrant do you use?
Did you update Vagrant recently?
Could you tell me which version of ailispaw/barge you use?

Older ailispaw/barge doesn't work well with the recent versions of Vagrant.
Vagrant has modified its internal functions recently.

Thanks.
