### ISSUE TITLE
Errors after Virtualbox and Vagrant update then vagrant up

### ISSUE THREAD

**Issue by echizenyayota** [wckr/wocker#57]
昨日、virtualboxとvagrant のバージョンアップをしました。

- virtualbox : 5.0.0r101573 → 5.1.12r112440
- vagrant : 1.7.4 → 1.9.1

そのせいかwocer ディレクトリから`vagrant up`をすると添付画像のようなエラーが出ます。
Vagrantfileに問題があると思いますが、どのように修正すればよろしいでしょうか？

ご存知の方がいらっしゃいましたら、よろしくお願いします。
<img width="914" alt="14_2" src="https://cloud.githubusercontent.com/assets/8636269/21668778/5fd79020-d348-11e6-97de-3aea255f1d83.png">

**Comment by ailispaw** [comment]
@echizenyayota 
"ailispaw/docker-root" と出ているのでかなり古い `Vagrantfile` を使っておられます。
最新のものは
https://github.com/wckr/wocker/blob/master/Vagrantfile
になりますので、ご確認下さい。
<del>一度現在の `Vagrantfile` をバックアップしてから、
最新のものに差し替えてお試しください。</del>

**Comment by ailispaw** [comment]
@echizenyayota
すみません。その他のファイルも更新されておりますので、
ディレクトリ全体をバックアップしたのち、
再度
https://wckr.github.io/
の手順から wocker を導入して下さい。
その後、バックアップから data ディレクトリをコピーし戻すと良いでしょう。

**Comment by ailispaw** [comment]
git がおわかりでしたら、git で最新のレポジトリを取得してもいいと思います。

**Comment by echizenyayota** [comment]
@ailispaw さん。さっそくのコメントありがとうございます。
現在の`Vagrantfile`を`Vagrantfile_1`とコピーしてwockerディレクトリに残し、新しい`Vagrantfile`を上記のページのものに差し替えて`vagrant up`しました。すると途中で通信ができなくなり、添付の画像のような状態になりました。次はどのような対応をすればよろしいでしょうか？

<img width="705" alt="15" src="https://cloud.githubusercontent.com/assets/8636269/21669126/0ba73aba-d34c-11e6-9861-36b6622b8357.png">

**Comment by ailispaw** [comment]
`vagrant destroy` をして、一度クリーンな状態にしてから、試してみて下さい。
また、上記にも書きましたが、`Vagrantfile` だけじゃなくて、wocker のレポジトリのファイルを全て更新して下さい。

**Comment by echizenyayota** [comment]
@ailispaw さん。
たびたびのアドバイスありがとうございます。
古いWockerに格納されていたコンテナの移動について、2つ質問があります。

---

**1.**
添付画像1枚目の右側はデスクトップに退避させた古いWockerのdataです。
例えば`wp_design_getting_started`というコンテナを、新しいWockerの元でも使おうと思えば、左側のホームディレクトリに移した上で、

$ wocker run --name wp_design_getting_started

というコマンンドを実行することになると思います。ところが、その状態で wocker.devにアクセスしても
デフォルトのtwentysixteenが表示されます。この状態は、データベースのインポートが出来ていないためにやむを得ないことなのでしょうか？

自分で作成している主要なテーマについては、先日教えてもらった[DockerによるWockerのイメージ化](https://github.com/wckr/wocker/issues/54)でDockerHubに保存しています。なので、Wockerを新しくしたことによる影響はほとんどないのですが、wp_design_getting_startedのみまだイメージ化していなかったので聞いてみました。

なお、wp_design_getting_startedは、オリジナルのテーマを作成しています。

**2.**
DockerHubからpullしてきたイメージをコンテナ化するときに、Macのハードディスクにマウントすることはできないのでしょうか？Docker自体が仮想化環境であるため、やむを得ないことでしょうか？
（添付画像2枚目）

---

お忙しいところ誠におそれいりますが、一度ご確認いただければ幸いです。

<img width="1170" alt="16" src="https://cloud.githubusercontent.com/assets/8636269/21673001/915405d6-d369-11e6-853a-286828a37317.png">

<img width="1133" alt="17" src="https://cloud.githubusercontent.com/assets/8636269/21672971/58ab9c44-d369-11e6-9261-9baa9690b352.png">

**Comment by ailispaw** [comment]
まず、１についてですが、
データベースのバックアップ／リストアが出来ない状態ですと、設定は初期値のままになってしまうので、そのような状態になってしまいます。
ただ、WordPressのテーマのPHPのファイルになっている部分はそのままの状態で残っているはずですので、適切に設定をすれば復活させられるのではないでしょうか。

**Comment by ailispaw** [comment]
２についてですが、
これは Wocker 固有の話ではないですね。
Docker のコンテナは、コンテナ側からホストのフォルダを参照する形なので、Macからマウントすることは通常（NFSとか別の方法を使わない限り）出来ません。

そのかわり、コンテナの内容は `docker cp` コマンドでコピー（取り出すことが）出来ます。
`docker cp <コンテナ名>:<コンテナ内ファイル／フォルダ名> <コピー先ファイル／フォルダ名>`
`docker cp e-yota:/var/www/wordpress ./data/e-yota`
のような感じですが、詳細はDockerのドキュメントをご確認下さい。

**Comment by ixkaito** [comment]
@ailispaw さん
もろもろありがとうございます。

@echizenyayota さん

**1** については @ailispaw さんの書いたとおりです。データベースをエクスポートしていれば、`wocker run --name wp_design_getting_started` 後、インポートすれば元に戻ります。

**2** については、`wocker run` コマンドにイメージを指定すればできます。
今回の場合: `wocker run --name e-yota echizenya/e-yota_image:latest`
詳しくは[こちら](https://wckr.github.io/commands/#h3-2)を確認ください。

**Comment by echizenyayota** [comment]
@ailispawさん。@ixkaito さん。
たくさんのアドバイスありがとうございます！

**1.**

@ailispawさん。

>データベースのバックアップ／リストアが出来ない状態ですと、設定は初期値のままになってしまうので、そのような状態になってしまいます。

了解です！
VirtualboxとVagrantをアップデートする前にデータベースをエクスポートすべきでしたね。
ただ、おっしゃるようにPHPのオリジナルテーマは残っていました。
今後の教訓といたします。

**2.**

@ixkaito さん。

>`wocker run` コマンドにイメージを指定すればできます。

おっしゃるとおりに`wocker run --name e-yota echizenya/e-yota_image:latest`をすると
添付の画像のとおり、MacのHDDに`e-yota`をマウントさせることができました（添付画像1枚目）

@ailispawさん。

>そのかわり、コンテナの内容は docker cp コマンドでコピー（取り出すことが）出来ます。

こちらも`docker cp wocker_5:/var/www/wordpress ./data/wocker_5`で取り出すことができました。
（添付画像2枚目）

参考ページ
https://docs.docker.com/engine/reference/commandline/cp/

---

もろもろありがとうございます。これでまたWordPressテーマ開発がやりやすくなりました！


<img width="1215" alt="3" src="https://cloud.githubusercontent.com/assets/8636269/21712913/890aa8c2-d43a-11e6-9633-40d6c550c476.png">
<img width="1084" alt="4" src="https://cloud.githubusercontent.com/assets/8636269/21712924/9597ee6a-d43a-11e6-8ac4-78969db1473c.png">

**Comment by echizenyayota** [comment]
とりあえず、このissueはcloseしておきます。
