### ISSUE TITLE
wp-cli Issue

### ISSUE THREAD

**Issue by pedroapfilho** [wckr/wocker#58]
![screenshot from 2017-01-23 16-38-11](https://cloud.githubusercontent.com/assets/13142568/22248040/eb1291be-e223-11e6-9b8b-5894f6531542.png)

**Comment by ixkaito** [comment]
Hi, @pedrovp123 when does this warning show?

**Comment by pedroapfilho** [comment]
When i open the my Atom with the WordPress Suite: https://atom.io/packages/wordpress-suite

**Comment by ixkaito** [comment]
I'm not familiar with the Atom WordPress Suite. I think WordPress Suite was finding WP-CLI from your host machine (Mac or Windows). However, when you are using Wocker, WP-CLI is not installed on your host machine. It's installed on the Docker container. WordPress Suite may not be able to find it, so you got the warning. To use WP-CLI on Wocker, please `vagrant ssh` then run `wocker wp` commands. See: https://wckr.github.io/commands/#h3-8

**Comment by pedroapfilho** [comment]
Alright, thanks!
