### ISSUE TITLE
How change the domain wocker.dev?

### ISSUE THREAD

**Issue by pedroapfilho** [wckr/wocker#59]
When i tried to change the domain I broke everything, there's some easy way to do this?

**Comment by ixkaito** [comment]
Could you tell me what's the reason you want to change the domain of wocker.dev?

**Comment by pedroapfilho** [comment]
I'm dumb as fuck, i see now how it works, thanks

**Comment by vukers** [comment]
@ixkaito If I need to connect to the site using mobile on the same network, I am unable to access using http://wocker.dev. Also, the direct IP address does not work. How can we access the site?

**Comment by ixkaito** [comment]
Hi @vukers. This is not a Wocker issue but a vagrant (or virtual machine) issue. Maybe the easiest way to share http://wocker.dev on your local network is [Browsersync](https://www.browsersync.io/).

1.  Install Node.js
2.  Install Browsersync
    ```
    npm install -g browser-sync
    ```
3.  Start Browsersync
    ```
    $ browser-sync start -p wocker.dev
    ```

Then you'll be able to connect to the external URL using your mobile which is on the same network.
