### ISSUE TITLE
Accessing the database from host OS

### ISSUE THREAD

**Issue by kadoppe** [wckr/wocker#6]
How do I access the database on wocker from a client on host OS?

**Comment by ixkaito** [comment]
You can use a Wocker or Docker command `$ wocker exec` (`$ docker exec`) to enter a running container.

e.g.

```
$ vagrant ssh
```

```
core@wocker ~ $ wocker exec -it CONTAINER bash
```

```
root@****:/var/www/wordpress# mysql -uwordpress -pwordpress
```

Then, you will log in to the MySQL.
Additional, WP CLI is installed, you can also use it to operate the DB.

e.g.

```
root@****:/var/www/wordpress# wp --allow-root db
```

Note: the `--allow-root` option is required.

**Comment by kadoppe** [comment]
Thanks! I successfully accessed the database.
