### ISSUE TITLE
Can I access the phpmyadmin on wocker?

### ISSUE THREAD

**Issue by pedroapfilho** [wckr/wocker#64]
I want to see if some options were put on the sql, but how can I access the mysql? 

tks

**Comment by ixkaito** [comment]
Hi @pedrofilho20,

I recommend you [Sequel Pro](https://www.sequelpro.com/) or [Workbench](https://www.mysql.com/products/workbench/).

Host: `wocker.dev` or `10.0.23.16`
Username: `wordpress`
Password: `wordpress`
Database: `wordpress`
Port: `3306`

![sequelpro](https://cloud.githubusercontent.com/assets/5457539/24048448/46050f40-0b6c-11e7-9da9-b46bfe7dbb14.png)
