### ISSUE TITLE
Moving Wocker to a new computer

### ISSUE THREAD

**Issue by ixkaito** [wckr/wocker#67]
@joeynimu said:

> Hi,
>
> I am not sure if this is an issue really more than just a question.
>
> I want to switch machines for my current one is a bit old and it is becoming slow. So the question is, how do I move all my wocker projects from my old mac to my new one ensuring that everything will run seamlessly on the new machine?
> I presume first thing first is that I have to install wocker on the new machine which I have. Do  I have to copy the whole of the data directory and manually export the databases or is there another simpler way?
>
> Many Thanks for Wocker. It has really eased by WP development process.

**Comment by ixkaito** [comment]
Hi @joeynimu ,

Sorry for the inconvenience. You have to manually export the databases and copy the whole of the data directory to your new machine. On your new machine, `wocker run --name EXISTINGSITE` will create a container using existing files. Then, `wocker wp db import wordpress.sql` will put the site back.

There is another way: https://gist.github.com/ailispaw/1e8f87f0a0def8e09351479d5adc1492. This tool packages a single container including files and the database to a Docker image. You can push it to Docker Hub, and pull it from your new machine. I'm planning to merge this into Wocker's next version.

Hope this helps :)

**Comment by joeynimu** [comment]
Hi @ixkaito ,

Thank you so much for your swift response. This has really helped me.

Cheers
