### ISSUE TITLE
Ailispaw/barge update issue

### ISSUE THREAD

**Issue by VesterDe** [wckr/wocker#69]
I just updated the box to 2.5.4 and wocker seems to have stopped working. Vagrant is up, wp cli works, but opening wocker.dev (or pinging it) just loads perpetually and sometimes times out after a minute or two.

It's quite confusing. I downgraded back to 2.5.3 but it persists. I've cleared dns and disabled firewall so far without change.

I then made a fresh wocker install in a different directory and even that didn't work.

Is anyone else getting this, or has any idea what might be going on?

**Comment by ailispaw** [comment]
Hi @VesterDe ,

Thank you for letting us know the issue.

Could you tell me your OS, its version, and the version of Vagrant and VirtualBox you use?

**Comment by VesterDe** [comment]
Arch Linux, 4.11.9-1-ARCH kernel
Vagrant 1.9.7
VirtualBox 5.1.24r117012

It may just be something I did with my system in the last few days... I'll update this if I manage to fix it, any hints are appreciated.

**Comment by ailispaw** [comment]
What is the line of `wocker.dev` in the `/etc/hosts` during and after vagrant up?

**Comment by VesterDe** [comment]
10.0.23.16  wocker.dev  # VAGRANT: 3413491252ddb7158ede8f207f9df701 (wocker) / 65f3a83e-a8ff-4804-b48e-baf75a180f58

**Comment by ailispaw** [comment]
Hmm. It looks good.
Can you ping to `10.0.23.16` and/or `wocker.dev`?

**Comment by VesterDe** [comment]
I agree yes.

No response from either the IP or the URL. However, if I ssh into vagrant, they do work.

`wocker ~ $ ping wocker.dev
PING wocker.dev (127.0.1.1): 56 data bytes
64 bytes from 127.0.1.1: seq=0 ttl=64 time=0.283 ms`

**Comment by ailispaw** [comment]
VirtualBox 5.1.24 released yesterday, I guess it may be the cause.

How is the output of `ifconfig` in the wocker VM?

**Comment by VesterDe** [comment]
Ah yes, maybe that was it...

ifconfig says this:

docker0   Link encap:Ethernet  HWaddr 02:42:E6:95:93:19  
          inet addr:172.17.0.1  Bcast:0.0.0.0  Mask:255.255.0.0
          inet6 addr: fe80::42:e6ff:fe95:9319/64 Scope:Link
          UP BROADCAST RUNNING MULTICAST  MTU:1500  Metric:1
          RX packets:3 errors:0 dropped:0 overruns:0 frame:0
          TX packets:7 errors:0 dropped:0 overruns:0 carrier:0
          collisions:0 txqueuelen:0 
          RX bytes:216 (216.0 B)  TX bytes:738 (738.0 B)

eth0      Link encap:Ethernet  HWaddr 08:00:27:79:32:FC  
          inet addr:10.0.2.15  Bcast:10.0.2.255  Mask:255.255.255.0
          inet6 addr: fe80::a00:27ff:fe79:32fc/64 Scope:Link
          UP BROADCAST RUNNING MULTICAST  MTU:1500  Metric:1
          RX packets:359 errors:0 dropped:0 overruns:0 frame:0
          TX packets:235 errors:0 dropped:0 overruns:0 carrier:0
          collisions:0 txqueuelen:1000 
          RX bytes:37477 (36.5 KiB)  TX bytes:33632 (32.8 KiB)

eth1      Link encap:Ethernet  HWaddr 08:00:27:00:96:DC  
          inet addr:10.0.23.16  Bcast:0.0.0.0  Mask:255.255.255.0
          inet6 addr: fe80::a00:27ff:fe00:96dc/64 Scope:Link
          UP BROADCAST RUNNING MULTICAST  MTU:1500  Metric:1
          RX packets:0 errors:0 dropped:0 overruns:0 frame:0
          TX packets:13 errors:0 dropped:0 overruns:0 carrier:0
          collisions:0 txqueuelen:1000 
          RX bytes:0 (0.0 B)  TX bytes:1526 (1.4 KiB)

lo        Link encap:Local Loopback  
          inet addr:127.0.0.1  Mask:255.0.0.0
          inet6 addr: ::1/128 Scope:Host
          UP LOOPBACK RUNNING  MTU:65536  Metric:1
          RX packets:4 errors:0 dropped:0 overruns:0 frame:0
          TX packets:4 errors:0 dropped:0 overruns:0 carrier:0
          collisions:0 txqueuelen:1 
          RX bytes:336 (336.0 B)  TX bytes:336 (336.0 B)

veth5cd4399 Link encap:Ethernet  HWaddr 5A:CD:7C:A4:07:5F  
          inet6 addr: fe80::58cd:7cff:fea4:75f/64 Scope:Link
          UP BROADCAST RUNNING MULTICAST  MTU:1500  Metric:1
          RX packets:3 errors:0 dropped:0 overruns:0 frame:0
          TX packets:17 errors:0 dropped:0 overruns:0 carrier:0
          collisions:0 txqueuelen:0 
          RX bytes:258 (258.0 B)  TX bytes:1734 (1.6 KiB)

**Comment by ailispaw** [comment]
ifconfig looks good as well.
vagrant also may be a candidate for the cause.
Could you try to downgrade virtualbox and/or vagrant?

**Comment by VesterDe** [comment]
I'll try tomorrow (out of office in a bit), thanks for the help so far.

**Comment by lakyller** [comment]
The same problem with me, after virtualbox update to version 5.1.24.
Update for Vagrant was done earlier.

**Comment by VesterDe** [comment]
Yep, can confirm, downgraded virtualbox to 5.1.22 and it fixed the problem.

**Comment by ailispaw** [comment]
Thank you for the confirmation, guys.

Also I found same issues on an other repo and its solution.

Vagrant up fails with VirtualBox 5.1.24 · Issue #8793 · mitchellh/vagrant
https://github.com/mitchellh/vagrant/issues/8793

[SOLVED] Can not ping virtualbox box after latest update (5.1.24-1) / Networking, Server, and Protection / Arch Linux Forums
https://bbs.archlinux.org/viewtopic.php?id=228365

#16911 (hostonly network broken on 5.1.24) – Oracle VM VirtualBox
https://www.virtualbox.org/ticket/16911

**Comment by ailispaw** [comment]
FYI:
Mac OS X 10.10.5, Vagrant 1.9.5 and VirtualBox 5.1.24 work fine for me.

Hi @lakyller,
Is your host OS Arch Linux?

**Comment by lakyller** [comment]
No my is: Ubuntu 16.04.2 LTS
But after I back to VirtualBox 5.1.22 everything works fine, again.

**Comment by ailispaw** [comment]
@lakyller Thanks.

**Comment by VesterDe** [comment]
This is presumably fixed in yesterdays release of [5.1.26](https://www.virtualbox.org/ticket/16911), if someone upgrades and checks, we can close the issue.

**Comment by VesterDe** [comment]
Yeah, wocker works again with Virtuablx 5.1.26 for me. Closing this.

**Comment by ailispaw** [comment]
Changelog – Oracle VM VirtualBox
https://www.virtualbox.org/wiki/Changelog#v26

> Linux hosts: properly bring up host-only network interfaces with iproute (5.1.24 regression; bug #16911)
