### ISSUE TITLE
Sharing DBs across machines

### ISSUE THREAD

**Issue by jcpeden** [wckr/wocker#7]
Any suggestions on sharing the DB across different machines? I develop on an iMac at home and a Macbook when I'm on the road.

**Comment by ixkaito** [comment]
The simplest way is probably using WP-CLI.

**1. Machine A: enter the running container**

```
core@wocker ~ $ wocker exec -it CONTAINER bash
```

**2. Machine A: export the database to a file (`wordpress.sql`)**

```
root@****:/var/www/wordpress# wp --allow-root db export
```

**3. Copy `wordpress.sql` to machine B**

**4. Machine B: enter the running container**

```
core@wocker ~ $ wocker exec -it CONTAINER bash
```

**5. Machine B: import database from a file (`wordpress.sql`)**

```
root@****:/var/www/wordpress# wp --allow-root db import wordpress.sql
```

Please also refer to #6.
More information about WP-CLI: http://wp-cli.org/

**Comment by jcpeden** [comment]
Outstanding - I'm new to Docker so getting used to the idea of running containers rather than unique Vagrant boxes.

**Comment by ixkaito** [comment]
Thanks! Docker container is really faster than vagrant box. I think you can save much time.
