### ISSUE TITLE
The WordPress site is not displayed even when Wocker is started.（Wockerを起動させてもWordPressサイトが表示されません）

### ISSUE THREAD

**Issue by echizenyayota** [wckr/wocker#71]
いつもお世話になっております。
下記の質問につきましてご存知の方がいらっしゃいましたら、ご教示を願います。

---

## 【質問の主旨】

既存のコンテナであるhogeを

`$ wocker start hoge` 

で起動させてもWordPressサイトが表示されません。どこを確認して修正すればよろしいでしょうか？

### 1.
ターミナルの画面から下記のコマンドを入力すると、Wockerの画面に入ることはできます

```
$ cd wocker
$ vagrant up
$ vagrant ssh
wocker ~ $
``` 

### 2.
```
$ wocker start hoge
hoge
```

1.の状態からhogeコンテナを起動させることはできます。

### 3.
ですがこの状態でブラウザにアクセスすると（https://wocker.dev/）

```
このサイトにアクセスできません
wocker.dev で接続が拒否されました。
```

と表示されてWordPressサイトが表示されません（ブラウザはGoogle　Chromeを使用しています）。

### 4.
vagrant upでローカル開発環境を起動させているときに表示される文言は以下の通りです。
全て白色の文字で、警告・注意を示す黄色の文字やエラーを示す赤色の文字はありませんでした。

```
Bringing machine 'wocker' up with 'virtualbox' provider...
==> wocker: Checking if box 'ailispaw/barge' is up to date...
==> wocker: Clearing any previously set forwarded ports...
==> wocker: Clearing any previously set network interfaces...
==> wocker: Preparing network interfaces based on configuration...
    wocker: Adapter 1: nat
    wocker: Adapter 2: hostonly
==> wocker: Forwarding ports...
    wocker: 2375 (guest) => 2375 (host) (adapter 1)
    wocker: 22 (guest) => 2222 (host) (adapter 1)
==> wocker: Running 'pre-boot' VM customizations...
==> wocker: Booting VM...
==> wocker: Waiting for machine to boot. This may take a few minutes...
    wocker: SSH address: 127.0.0.1:2222
    wocker: SSH username: bargee
    wocker: SSH auth method: private key
==> wocker: Machine booted and ready!
==> wocker: [vagrant-hostsupdater] Checking for host entries
==> wocker: [vagrant-hostsupdater] Writing the following entries to (/etc/hosts)
==> wocker: [vagrant-hostsupdater]   10.0.23.16  wocker.dev  # VAGRANT: dc7e5c5b6adee79ad50c40129d6f32b5 (wocker) / 4873c4c2-fcee-499e-9bac-54018f8b044b
==> wocker: [vagrant-hostsupdater] This operation requires administrative access. You may skip it by manually adding equivalent entries to the hosts file.
==> wocker: Setting hostname...
==> wocker: Configuring and enabling network interfaces...
==> wocker: Mounting shared folders...
    wocker: /home/bargee/data => /Users/HiroshiFukui/wocker/data
==> wocker: Machine already provisioned. Run `vagrant provision` or use the `--provision`
==> wocker: flag to force provisioning. Provisioners marked to run always will still run.
fukuiyou-no-Mac

```

---

以上、よろしくお願い申し上げます。

**Comment by kitakado-h** [comment]
The page of wocker.dev is not displayed because Chrome is using it.

Chromeだからでしょう。動かない時は、複数のブラウザでもチェックしたほうが良いでしょう。
[Google Chromeで.devなどの開発DomainがHTTPSに変更される。](https://qiita.com/lara_bell/items/f7f3c5189530090229ed)

**Comment by echizenyayota** [comment]
@kitakado-h さん。コメントありがとうございます。Firefoxにしたらwocker.devで動作しました！(safariでは動きませんでした)。
<img width="815" alt="wockre_firefox" src="https://user-images.githubusercontent.com/8636269/34286855-d12bde3c-e726-11e7-8dfc-1f0ce7e1d459.png">

**Comment by echizenyayota** [comment]
I switched the browser to Firefox instead of Chrome, Wocker worked. From now on I will ask questions in English.

**Comment by matthewwoodard** [comment]
Can we easily change wocker.dev to wocker.test or wocker.local?

**Comment by ixkaito** [comment]
Thanks everyone. V1.2 is now available. It changes the `wocker.dev` to `wocker.test` to fix this issue.

Please `git pull` in your existing Wocker directory and then `wocker update` on your Wocker machine, or clone the repository again for a fresh installation.

To move your old containers from `wocker.dev` to `wocker.test`, please see https://wckr.github.io/tips/#h2-0.

Here's the [changelog](https://wckr.github.io/changelog/#h2-0).

**Comment by matthewwoodard** [comment]
Everything is working great! Thank you for doing this.
