### ISSUE TITLE
/opt/bin/wocker: line 470: nfirmation: command not found

### ISSUE THREAD

**Issue by kitakado-h** [wckr/wocker#73]
I'm using a Mac.
I updated wocker to version 1.2.
This sentence was displayed, but is there a problem?
--
/opt/bin/wocker: line 470: nfirmation: command not found
--

**Comment by ixkaito** [comment]
Please try to `wocker update` again. I think the warning will disappear.

**Comment by kitakado-h** [comment]
@ixkaito 
That went well.  Thank you for the advice.
