### ISSUE TITLE
Can not wordmove pull via ftp

### ISSUE THREAD

**Issue by akiya64** [wckr/wocker#76]
I tried wordmove via ftp, but shows error "lftp not found"
Because, Wordmove needs lftp package, but Wocker docker image does not include.

So I did `apt-get update && apt-get install -y lftp` for running wocker container, I can connect ftp server.
But can not pull theme file, refuse connection error.

May need more settings for lftp, I'm investigating.

**Comment by VesterDe** [comment]
This helped me once, I don't know if it's universal:

https://github.com/welaika/wordmove/issues/40#issuecomment-15900578

**Comment by akiya64** [comment]
Hi @VesterDe, I could pull theme via ftp by your helps.
I Installed lftp package and `echo "set ssl:verify-certificate no" >> ~/
.lftp.rc` into container.
Thanks!

**Comment by ixkaito** [comment]
Should we include `lftp` by default?

**Comment by akiya64** [comment]
Yes, need include lftp package.
I send PR for wckr/base-image.

**Comment by ixkaito** [comment]
@akiya64 Thanks!
