### ISSUE TITLE
 Requires PHP Zip module but it is not enabled on your server

### ISSUE THREAD

**Issue by irvngt** [wckr/wocker#79]
Hello I have a problem with the PHP Zip module, How do I enable this module?

**Comment by ixkaito** [comment]
Hello @irvingmn.

Here's how to install `php7.0-zip`:

__1. Runs or starts your container if it's not running__
   ```
   wocker ~ $ wocker run --name CONTAINER
   ```
__2. Executes `bash` on the container__
   ```
   wocker ~ $ wocker exec -it CONTAINER bash
   ```
__3. Updates the list of available packages and install `php7.0-zip`__
   ```
   root@****:/var/www/wordpress# apt update
   root@****:/var/www/wordpress# apt install php7.0-zip
   ```

I'm considering whether I should install `php7.0-zip` by default.
