### ISSUE TITLE
Change hostname and run multiple instances

### ISSUE THREAD

**Issue by jcpeden** [wckr/wocker#8]
> Copied as requested

Hi,

Fantastic use of Docker on this one - really impressed!

Would it be possible to setup a new instance at something other than wocker.dev e.g. mysite.dev?

Thanks

John

**Comment by ixkaito** [comment]
The URL of WordPress is saved in the Docker image. Therefore, to setup another one is not very easy.
If you are familiar with Docker and Dockerfile, it's possible.

Here's the repository of the Dockerfile of Wocker: https://github.com/wckr/wocker-dockerfile/tree/master/wheezy.
- Modify "wocker.dev" both in the Vagrantfile and Dockerfile.
- Build your own Docker image from the Dockerfile you modified.
- Use your own Docker image to `$ wocker run`.

e.g.

```
$ wocker run --name mysite jcpeden/mysite
```

In this case, `jcpeden/mysite` was your own Docker image.
