### ISSUE TITLE
Box not found

### ISSUE THREAD

**Issue by AKarmanov** [wckr/wocker#81]
It looks like https://atlas.hashicorp.com/ailispaw/barge is not existing anymore so the box cannot be downloaded. Any ideas on how to fix this?

**Comment by ailispaw** [comment]
Hi @AKarmanov ,

They has moved the repository to https://app.vagrantup.com/.
I think this is related to https://github.com/hashicorp/vagrant/issues/9442 and it has been fixed.

Please upgrade Vagrant to the latest.
Thank you.

**Comment by AKarmanov** [comment]
Updating Vagrant did it! Thanks for prompt response!
