### ISSUE TITLE
vagrant up did not complete

### ISSUE THREAD

**Issue by matwu37** [wckr/wocker#9]
Tried multiple times, everytime it stops at setting the name
or port collison

Any idea how to get it work or what causing the problem?

matthew.wu@X205 ~
$ git clone https://github.com/wckr/wocker.git && cd wocker
Cloning into 'wocker'...
remote: Counting objects: 109, done.
remote: Compressing objects: 100% (6/6), done.
remote: Total 109 (delta 1), reused 0 (delta 0), pack-reused 103
Receiving objects: 100% (109/109), 18.00 KiB | 0 bytes/s, done.
Resolving deltas: 100% (45/45), done.
Checking connectivity... done.

matthew.wu@X205 ~/wocker
$ vagrant up
Bringing machine 'default' up with 'virtualbox' provider...
==> default: Importing base box 'coreos-stable'...
==> default: Matching MAC address for NAT networking...
==> default: Checking if box 'coreos-stable' is up to date...
==> default: Setting the name of the VM: wocker_default_1426897888404_23903

<code>
==> default: Fixed port collision for 22 => 2222. Now on port 2200.
</code>

P.S. On Windows 7 with cygwin

**Comment by ixkaito** [comment]
Did you add "wocker.dev 172.17.8.23" to your hosts-file?

**Comment by matwu37** [comment]
I do have hostsupdater install? Do I still need to do so?
And do it before vagrant up?

**Comment by ixkaito** [comment]
I don't know well about vagrant-hostsupdater for Windows. I heard it doesn't work well for Windows.

These issues may help you.
https://github.com/cogitatio/vagrant-hostsupdater/issues/11
https://github.com/kalamuna/kalastack/issues/79

However, I think adding "wocker.dev 172.17.8.23" by yourself is the simplest way.

**Comment by matwu37** [comment]
I am still having problems at this process, after modifying the host file

==> default: Setting the name of the VM: wocker_default_1426897888404_23903

It's just hangs for a long long time, any idea what causing it?

**Comment by ixkaito** [comment]
Wocker uses CoreOS on Vagrant. Does the official CoreOS Vagrant work for you?

```
$ git clone https://github.com/coreos/coreos-vagrant.git && cd coreos-vagrant
```

```
$ vagrant up
```

Please try if this finishes without error, and you can `$ vagrant ssh` after it.
For more information, please see https://coreos.com/docs/running-coreos/platforms/vagrant/.
